apiVersion: v1
kind: ReplicationController
metadata:
 name: rp-controller
 labels:
   name: rp
   app: myapp
spec:
 replicas: 3
 template:
   metadata:
     name: mypod
     labels: 
        name: mypod
   spec:
     containers:
       - name: nginx
         image: nginx
         ports:
          - containerPort: 8080
            name: nginxport
